//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleGroupPermissions = new HashSet<RoleGroupPermission>();
            this.Users = new HashSet<User>();
        }
    
        public byte RoleID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RoleGroupPermission> RoleGroupPermissions { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
